[project]
name = "strands-mcp"
version = "0.1.0"
description = "MCP server for strands information crawling and code generation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.2",
    "httpx",
    "beautifulsoup4",
]
